const state = { selected:"Bitterroot", data:{}, charts:{}, favorites: JSON.parse(localStorage.getItem("favorites") || "[]"), favoritesOnly:false };
const allGauges = () => RIVERS.flatMap(r => getRiverGauges(r).map(g => ({...g, river:r.name})));
function url(site, parameter){ return "https://waterservices.usgs.gov/nwis/iv/?" + new URLSearchParams({ format:"json", sites:site, parameterCd:parameter, period:"P7D", siteStatus:"all" }).toString(); }
function cToF(c){ return c * 9 / 5 + 32; }
function isValidTempF(tempF){ return Number.isFinite(tempF) && tempF >= 32 && tempF <= 85; }
function series(json, temp=false){ return (json?.value?.timeSeries?.[0]?.values?.[0]?.value || []).map(p => ({ time:p.dateTime, value:Number(p.value) })).filter(p => Number.isFinite(p.value)).map(p => ({ time:p.time, value: temp ? cToF(p.value) : p.value })).filter(p => !temp || isValidTempF(p.value)); }
async function fetchSeries(site, parameter, temp=false){ const res = await fetch(url(site, parameter)); if(!res.ok) throw new Error("USGS error"); return series(await res.json(), temp); }
function latest(arr){ return arr?.length ? arr[arr.length-1] : null; }
function fmtFlow(v){ return Number.isFinite(v) ? Math.round(v).toLocaleString() + " CFS" : "--"; }
function fmtTemp(v){ return Number.isFinite(v) ? v.toFixed(1) + "°F" : "--"; }
function fmtTime(iso){ return iso ? new Date(iso).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}) : "Unavailable"; }
function fmtDate(iso){ const d = new Date(iso); return `${d.getMonth()+1}/${d.getDate()}`; }
function tempStatus(t){ if(!Number.isFinite(t)) return {label:"No temp", cls:"", dot:""}; if(t >= 67) return {label:"Too Hot", cls:"hot", dot:"status-hot"}; if(t >= 65) return {label:"Warm", cls:"warm", dot:"status-warm"}; return {label:"Good", cls:"good", dot:"status-good"}; }
function sample(arr, max=160){ if(arr.length <= max) return arr; const step = Math.ceil(arr.length / max); return arr.filter((_,i) => i % step === 0); }
function findGauge(id){ return allGauges().find(g => g.id === id); }
function getHeadlineGauge(river){ const gauges = getRiverGauges(river); return gauges.find(g => g.id === river.headline) || gauges[0]; }

function currentSeason(){ const month = new Date().getMonth() + 1; if(month === 12 || month <= 2) return "winter"; if(month >= 3 && month <= 5) return "spring"; if(month === 6) return "early_summer"; if(month >= 7 && month <= 8) return "summer"; return "fall"; }
function scoreHatch(rule, tempF){ if(!Number.isFinite(tempF)) return null; const season = currentSeason(); const seasonScore = rule.season.includes(season) ? 25 : 0; let tempScore = 0; const [idealLow, idealHigh] = rule.idealTemp; if(tempF >= idealLow && tempF <= idealHigh){ tempScore = 75; } else if(tempF >= rule.startTemp && tempF < idealLow){ tempScore = 45 + ((tempF - rule.startTemp) / (idealLow - rule.startTemp)) * 30; } else if(tempF > idealHigh && tempF <= rule.fadeTemp){ tempScore = 75 - ((tempF - idealHigh) / (rule.fadeTemp - idealHigh)) * 35; } else { tempScore = 0; } const score = Math.round(seasonScore + tempScore); let status = "Possible"; if(score >= 85) status = "Excellent"; else if(score >= 70) status = "Likely"; else if(score >= 50) status = "Possible"; else status = "Unlikely"; return { ...rule, score, status }; }
function renderHatchPanel(river){ const rules = window.HATCH_DATABASE?.[river.name]; if(!rules) return ""; const headline = getHeadlineGauge(river); const temp = latest(state.data[headline?.id]?.temp || [])?.value; if(!Number.isFinite(temp)){ return `<div class="panel hatch-panel"><h3>Likely Hatches</h3><p class="muted">Waiting for a valid water temperature from the headline gauge.</p></div>`; } const hatches = rules.map(rule => scoreHatch(rule, temp)).filter(Boolean).filter(h => h.score >= 45).sort((a,b) => b.score - a.score).slice(0,5); return `<div class="panel hatch-panel"><div class="hatch-head"><div><h3>Likely Hatches</h3><p class="muted">Based on ${headline.name.replace(", MT","")} at ${fmtTemp(temp)}</p></div></div><div class="hatch-list">${hatches.map(h => `<div class="hatch-card"><div class="hatch-top"><strong>${h.name}</strong><span>${h.status}</span></div><div class="hatch-bar"><div style="width:${h.score}%"></div></div><div class="hatch-meta">${h.position} • ${h.timeOfDay} • Ideal ${h.idealTemp[0]}–${h.idealTemp[1]}°F</div></div>`).join("") || `<p class="muted">No strong hatch signals right now.</p>`}</div></div>`; }
function renderTabs(){ const tabs = document.getElementById("tabs"); tabs.innerHTML = RIVERS.map(r => `<button class="tab ${r.name===state.selected?'active':''}" onclick="selectRiver('${r.name}')">${r.name}</button>`).join(""); }
function renderFavoritesPanel(){ const panel = document.getElementById("favoritesPanel"); const favorites = state.favorites.map(findGauge).filter(Boolean); if(!favorites.length){ panel.classList.remove("active"); panel.innerHTML = ""; return; } panel.classList.add("active"); panel.innerHTML = `<div class="favorite-title"><h2>Favorite Gauges</h2><span class="muted">${favorites.length} saved</span></div><div class="favorite-list">${favorites.map(g => { const d = state.data[g.id] || {}; const f = latest(d.flow || []); const t = latest(d.temp || []); return `<div class="favorite-card" onclick="selectRiver('${g.river || findGauge(g.id)?.river || ""}')"><strong>${g.name}</strong><span>${fmtFlow(f?.value)}${Number.isFinite(t?.value) ? " • " + fmtTemp(t.value) : ""}</span></div>`; }).join("")}</div>`; }
function renderRiverCards(){ const grid = document.getElementById("riverGrid"); const rivers = state.favoritesOnly ? RIVERS.filter(r => getRiverGauges(r).some(g => state.favorites.includes(g.id))) : RIVERS; grid.innerHTML = rivers.map(r => { const gauges = getRiverGauges(r); const headline = getHeadlineGauge(r); const d = state.data[headline?.id] || {}; const f = latest(d.flow || []); const t = latest(d.temp || []); const st = tempStatus(t?.value); const favs = gauges.filter(g => state.favorites.includes(g.id)).length; const sectionText = r.sections ? r.sections.filter(s => !s.tributary).map(s => s.name.replace(r.name, "").trim()).join(" • ") : "No sections"; return `<article class="river-card ${r.name===state.selected?'selected':''}" onclick="selectRiver('${r.name}')"><div class="river-title"><span>${r.name}</span><span>${favs ? "★" : "›"}</span></div><div class="river-sub">Headline: ${headline?.name?.replace(", MT","") || "—"}</div><div class="river-metrics"><div class="mini"><div class="label">Flow</div><div class="value">${fmtFlow(f?.value)}</div></div><div class="mini"><div class="label">Temp</div><div class="value ${st.cls}">${fmtTemp(t?.value)}</div></div></div><div class="river-sub" style="margin-top:12px;">${gauges.length} gauges${r.sections ? " • " + sectionText : ""}</div></article>`; }).join("") || `<div class="empty panel">No favorite gauges yet. Star a gauge below.</div>`; }
function renderDetails(){ const root = document.getElementById("details"); const river = RIVERS.find(r => r.name === state.selected); if(!river) return; root.innerHTML = `<div class="section-title"><div><h2>${river.name}</h2><div class="section-subtitle">${getRiverGauges(river).length} curated gauges • live 7-day USGS flow and water temperature</div></div><a class="pill" target="_blank" rel="noopener" href="https://radar.weather.gov/">Radar ↗</a></div>${renderHatchPanel(river)}<div class="gauge-grid">${river.sections ? renderSectionedGauges(river) : getRiverGauges(river).map(g => gaugeHtml(g, river.name)).join("")}</div>`; getRiverGauges(river).forEach(g => drawGauge(g.id)); }
function renderSectionedGauges(river){ return river.sections.map(section => `<div class="group-title ${section.tributary ? "tributary" : ""}">${section.tributary ? "↳ " : ""}${section.name}</div>${section.gauges.map(g => gaugeHtml({...g, tributary:!!section.tributary}, river.name)).join("")}`).join(""); }
function gaugeHtml(g, river){ const d = state.data[g.id] || {}; const f = latest(d.flow || []); const t = latest(d.temp || []); const hasTemp = Number.isFinite(t?.value); const st = tempStatus(t?.value); const fav = state.favorites.includes(g.id); return `<article class="panel gauge" id="gauge-${g.id}"><div class="gauge-head"><div><h3>${g.name}</h3><div class="muted">${g.type ? g.type.charAt(0).toUpperCase() + g.type.slice(1) : "Gauge"} • Updated: ${fmtTime(f?.time)}</div></div><button onclick="toggleFavorite('${g.id}'); event.stopPropagation();">${fav ? "★" : "☆"}</button></div><div class="gauge-metrics"><div class="metric"><div class="label">Current Flow</div><div class="value">${fmtFlow(f?.value)}</div></div><div class="metric"><div class="label">Water Temp</div><div class="value ${st.cls}">${hasTemp ? fmtTemp(t.value) : "--"}</div></div><div class="metric"><div class="label">Condition</div><div class="value ${st.cls}"><span class="status-dot ${st.dot}"></span>${st.label}</div></div></div><div class="chart" id="chart-${g.id}"></div><div class="gauge-foot"><span>${d.error ? "Could not load gauge." : (hasTemp ? "Temp line included." : "Temperature not currently reported.")}</span><a href="https://waterdata.usgs.gov/monitoring-location/${g.id}/" target="_blank" rel="noopener">Live USGS Gauge ${g.id}</a></div></article>`; }
async function loadGauge(g){ try{ const [flow,temp] = await Promise.allSettled([fetchSeries(g.id,"00060"), fetchSeries(g.id,"00010",true)]); state.data[g.id] = { flow: flow.status === "fulfilled" ? flow.value : [], temp: temp.status === "fulfilled" ? temp.value : [], error: flow.status !== "fulfilled" }; }catch(e){ state.data[g.id] = {flow:[],temp:[],error:true}; } }
async function refreshAll(){ document.getElementById("lastUpdated").textContent = "Refreshing live USGS data..."; await Promise.all(allGauges().map(loadGauge)); updateSummary(); renderTabs(); renderFavoritesPanel(); renderRiverCards(); renderDetails(); document.getElementById("lastUpdated").textContent = "Last refreshed " + new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}); }
function updateSummary(){ const gauges = allGauges(); const loaded = gauges.filter(g => state.data[g.id]?.flow?.length).length; let cool=0,warm=0,hot=0; gauges.forEach(g => { const t = latest(state.data[g.id]?.temp || [])?.value; if(!Number.isFinite(t)) return; if(t >= 67) hot++; else if(t >= 65) warm++; else cool++; }); document.getElementById("gaugeCount").textContent = `${gauges.length} gauges`; document.getElementById("loadedCount").textContent = loaded; document.getElementById("coolCount").textContent = cool; document.getElementById("warmCount").textContent = warm; document.getElementById("hotCount").textContent = hot; }
function selectRiver(name){ state.selected = name; renderTabs(); renderRiverCards(); renderDetails(); document.getElementById("details").scrollIntoView({behavior:"smooth",block:"start"}); }
function toggleFavorite(id){ state.favorites = state.favorites.includes(id) ? state.favorites.filter(x => x !== id) : [...state.favorites, id]; localStorage.setItem("favorites", JSON.stringify(state.favorites)); renderFavoritesPanel(); renderRiverCards(); renderDetails(); }
function showFavorites(){ state.favoritesOnly = true; renderRiverCards(); }
function showAllRivers(){ state.favoritesOnly = false; renderRiverCards(); }
window.addEventListener("resize", () => { Object.values(state.charts).forEach(c => c.resize()); });
renderTabs(); renderRiverCards(); renderDetails(); refreshAll(); setInterval(refreshAll, 10 * 60 * 1000);
